Repository zabbix-community/helm-zabbix, pull requests merged in 2024-02, with the labels that each got.

#63 Add concurrencyPolicy value
  charts/zabbix/templates/cronjob-hanodes-autoclean.yaml
  charts/zabbix/values.yaml
Labels: documentation, enhancement

#60 Fix template bug in zabbix-server template with missing imagePullPolicy
  charts/zabbix/Chart.yaml
  charts/zabbix/README.md
  charts/zabbix/artifacthub-pkg.yml
  charts/zabbix/templates/deployment-zabbix-server.yaml
Labels: bug, documentation, good first issue

#59 Update GH Actions and configure dependabot
  .github/dependabot.yml
  .github/workflows/helm-chart-releaser.yml
  README.md
Labels: documentation, enhancement, good first issue

#58 codespell: Add CI job fixing spelling issues and fix them
  .github/workflows/linters.yml
  charts/zabbix/README.md
  charts/zabbix/README.md.gotmpl
  charts/zabbix/docs/README.md
  charts/zabbix/docs/example/README.md
  charts/zabbix/docs/example/kind/values.yaml
  charts/zabbix/values.yaml
Labels: documentation, enhancement, good first issue

#68 Changes aecio 02 13 2024
  .github/PULL_REQUEST_TEMPLATE.md
  charts/zabbix/Chart.yaml
  charts/zabbix/Makefile
  charts/zabbix/README.md
  charts/zabbix/README.md.gotmpl
  charts/zabbix/artifacthub-pkg.yml
  charts/zabbix/docs/example/kind/values.yaml
  charts/zabbix/docs/requirements.md
  charts/zabbix/templates/cronjob-hanodes-autoclean.yaml
  charts/zabbix/templates/daemonset-zabbix-agent.yaml
  charts/zabbix/templates/deployment-zabbix-server.yaml
  charts/zabbix/templates/deployment-zabbix-web.yaml
  charts/zabbix/templates/deployment-zabbix-webservice.yaml
  charts/zabbix/templates/job-init-db-schema.yaml
  charts/zabbix/templates/karpenter-00-default-provisioner.yaml
  charts/zabbix/templates/karpenter-00-nodeclass.yaml
  charts/zabbix/templates/karpenter-00-nodepool.yaml
  charts/zabbix/templates/secret-db-access.yaml
  charts/zabbix/templates/statefulset-postgresql.yaml
  charts/zabbix/templates/statefulset-zabbix-proxy.yaml
  charts/zabbix/values.yaml
Labels: documentation, enhancement

#72 feat: add serviceaccount
  charts/zabbix/README.md
  charts/zabbix/templates/cronjob-hanodes-autoclean.yaml
  charts/zabbix/templates/daemonset-zabbix-agent.yaml
  charts/zabbix/templates/deployment-zabbix-server.yaml
  charts/zabbix/templates/deployment-zabbix-web.yaml
  charts/zabbix/templates/deployment-zabbix-webservice.yaml
  charts/zabbix/templates/serviceaccount.yaml
  charts/zabbix/templates/statefulset-postgresql.yaml
  charts/zabbix/templates/statefulset-zabbix-proxy.yaml
  charts/zabbix/values.yaml
Labels: documentation, enhancement, good first issue

#73 feat: add more customization for labels
  charts/zabbix/README.md
  charts/zabbix/templates/_helpers.tpl
  charts/zabbix/templates/cronjob-hanodes-autoclean.yaml
  charts/zabbix/templates/daemonset-zabbix-agent.yaml
  charts/zabbix/templates/deployment-zabbix-server.yaml
  charts/zabbix/templates/deployment-zabbix-web.yaml
  charts/zabbix/templates/deployment-zabbix-webservice.yaml
  charts/zabbix/templates/statefulset-postgresql.yaml
  charts/zabbix/templates/statefulset-zabbix-proxy.yaml
  charts/zabbix/values.yaml
Labels: documentation, enhancement, good first issue
