Repository zabbix-community/helm-zabbix, pull requests merged in 2025-02, with the labels that each got.

#167 Solving issues 166 and 165
  charts/zabbix/Chart.yaml
  charts/zabbix/Makefile
  charts/zabbix/README.md
  charts/zabbix/artifacthub-pkg.yml
  charts/zabbix/docs/example/kind/values.yaml
  charts/zabbix/docs/requirements.md
  charts/zabbix/templates/daemonset-zabbix-agent.yaml
  charts/zabbix/templates/deployment-zabbix-java-gateway.yaml
  charts/zabbix/values.yaml
Labels: bug, documentation

#168 add lifecycle for zaby-proxy container in zabbix-proxy statefulset
  charts/zabbix/templates/statefulset-zabbix-proxy.yaml
  charts/zabbix/values.yaml
Labels: documentation, enhancement

#169 Publishing release 7.0.5
  CONTRIBUTING.md
  charts/zabbix/Chart.yaml
  charts/zabbix/README.md
  charts/zabbix/artifacthub-pkg.yml
Labels: documentation

#171 Generating new release 7.0.6
  CONTRIBUTING.md
  charts/zabbix/Chart.yaml
  charts/zabbix/README.md
  charts/zabbix/README.md.gotmpl
  charts/zabbix/artifacthub-pkg.yml
  charts/zabbix/docs/example/kind/values.yaml
  charts/zabbix/templates/statefulset-zabbix-proxy.yaml
  charts/zabbix/values.yaml
Labels: documentation
