Repository zabbix-community/helm-zabbix, pull requests merged in 2025-01, with the labels that each got.

#148 Rework postgres access, introduce automated install/upgrade tests
  .github/workflows/linters.yml
  .github/workflows/tests.yaml
  charts/zabbix/Chart.yaml
  charts/zabbix/README.md.gotmpl
  charts/zabbix/templates/_helpers.tpl
  charts/zabbix/templates/cronjob-hanodes-autoclean.yaml
  charts/zabbix/templates/deployment-zabbix-server.yaml
  charts/zabbix/templates/job-create-upgrade-db.yaml
  charts/zabbix/templates/secret-db-access.yaml
  charts/zabbix/templates/tests/test-server-connection.yaml
  charts/zabbix/templates/tests/test-web-connection.yaml
  charts/zabbix/values.yaml
Labels: bug, documentation, break change

#150 Rework labels, deprecate old compatibility switches
  charts/zabbix/README.md.gotmpl
  charts/zabbix/templates/NOTES.txt
  charts/zabbix/templates/_helpers.tpl
  charts/zabbix/templates/cronjob-hanodes-autoclean.yaml
  charts/zabbix/templates/daemonset-zabbix-agent.yaml
  charts/zabbix/templates/deployment-webdriver.yaml
  charts/zabbix/templates/deployment-zabbix-java-gateway.yaml
  charts/zabbix/templates/deployment-zabbix-server.yaml
  charts/zabbix/templates/deployment-zabbix-web.yaml
  charts/zabbix/templates/deployment-zabbix-webservice.yaml
  charts/zabbix/templates/ingress.yaml
  charts/zabbix/templates/job-create-upgrade-db.yaml
  charts/zabbix/templates/role-ha-helper.yaml
  charts/zabbix/templates/rolebinding-ha-helper.yaml
  charts/zabbix/templates/secret-db-access.yaml
  charts/zabbix/templates/service.yaml
  charts/zabbix/templates/serviceaccount-ha-helper.yaml
  charts/zabbix/templates/serviceaccount.yaml
  charts/zabbix/templates/statefulset-postgresql.yaml
  charts/zabbix/templates/statefulset-zabbix-proxy.yaml
  charts/zabbix/values.yaml
Labels: bug, documentation, break change

#153 Fix bugs and adjust in documentation
  CONTRIBUTING.md
  README.md
  charts/zabbix/Chart.yaml
  charts/zabbix/README.md
  charts/zabbix/README.md.gotmpl
  charts/zabbix/artifacthub-pkg.yml
  charts/zabbix/docs/example/README.md
  charts/zabbix/docs/example/kind/values.yaml
  charts/zabbix/docs/requirements.md
  charts/zabbix/templates/NOTES.txt
Labels: bug, documentation

#140 Add namespace declaration to manifests
  charts/zabbix/templates/cronjob-hanodes-autoclean.yaml
  charts/zabbix/templates/daemonset-zabbix-agent.yaml
  charts/zabbix/templates/deployment-webdriver.yaml
  charts/zabbix/templates/deployment-zabbix-java-gateway.yaml
  charts/zabbix/templates/deployment-zabbix-server.yaml
  charts/zabbix/templates/deployment-zabbix-web.yaml
  charts/zabbix/templates/deployment-zabbix-webservice.yaml
  charts/zabbix/templates/ingress.yaml
  charts/zabbix/templates/job-create-upgrade-db.yaml
  charts/zabbix/templates/role-ha-helper.yaml
  charts/zabbix/templates/rolebinding-ha-helper.yaml
  charts/zabbix/templates/secret-db-access.yaml
  charts/zabbix/templates/service.yaml
  charts/zabbix/templates/serviceaccount-ha-helper.yaml
  charts/zabbix/templates/serviceaccount.yaml
  charts/zabbix/templates/statefulset-postgresql.yaml
  charts/zabbix/templates/statefulset-zabbix-proxy.yaml
  charts/zabbix/templates/tests/test-server-connection.yaml
  charts/zabbix/templates/tests/test-web-connection.yaml
Labels: enhancement, good first issue

#155 New release 7.0.2
  charts/zabbix/Chart.yaml
  charts/zabbix/README.md
  charts/zabbix/README.md.gotmpl
  charts/zabbix/artifacthub-pkg.yml
Labels: documentation

#156 fix: removed global nodeSelector to apply the parameter individually …
  charts/zabbix/templates/cronjob-hanodes-autoclean.yaml
  charts/zabbix/templates/daemonset-zabbix-agent.yaml
  charts/zabbix/templates/deployment-webdriver.yaml
  charts/zabbix/templates/deployment-zabbix-java-gateway.yaml
  charts/zabbix/templates/deployment-zabbix-server.yaml
  charts/zabbix/templates/deployment-zabbix-web.yaml
  charts/zabbix/templates/deployment-zabbix-webservice.yaml
  charts/zabbix/templates/job-create-upgrade-db.yaml
  charts/zabbix/templates/statefulset-postgresql.yaml
  charts/zabbix/templates/statefulset-zabbix-proxy.yaml
  charts/zabbix/templates/tests/test-server-connection.yaml
  charts/zabbix/templates/tests/test-web-connection.yaml
  charts/zabbix/values.yaml
Labels: enhancement, good first issue

#157 New release: 7.0.3
  charts/zabbix/Chart.yaml
  charts/zabbix/README.md
  charts/zabbix/artifacthub-pkg.yml
Labels: documentation

#159 Improvements in general documentation of this repo
  HISTORY.md
  README.md
  charts/zabbix/Makefile
  charts/zabbix/docs/requirements.md
Labels: documentation
